### ISSUE TITLE
unable to locate the git folder after re-installing rsm setup

### ISSUE THREAD

**Issue by akshayreddykotha** [radiant-rstats/docker#59]
Hi,

I have recently re-installed the rsm setup after a year (the last version was during April 2021). I have changed the user name compared to the initial installation (2019) of rsm setup. Now, I couldn't locate the git folder just like I always had access with my old user name under the C: drive. By reading this [issue](https://github.com/radiant-rstats/docker/issues/25), I see that the user remains jovyan for everyone in the environment.

There is no problem in using jupyter or R but if I want to upload data from an older git folder or even new data or files, I prefer to directly move it in the windows explorer rather than adding them to the git folder by drag and dropping on to the git folder shown on the below screen:

![image](https://user-images.githubusercontent.com/28220296/171736895-ed2dfd35-a15f-42c2-9b6d-ced12bbded48.png)

1. How can I access the newer git folder on windows explorer?

**Comment by vnijs** [comment]
If you open an Ubuntu terminal and then type `cd` you should be in the directory used by Docker. Disk IO is much faster if you put files here so that is what I recommend. Now type `explorer.exe .` in the Ubuntu terminal and a windows explorer folder should pop up that you can use to move files around.
